swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/UserProfile"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update User Profile API
      description: API for updating user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile updated successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: User Accounts
      description: API for getting all user accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      responses:
        "200":
          description: Accounts retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Account"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/accounts/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Account Details
      description: API for getting account details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: Account ID
          type: string
          required: true
      responses:
        "200":
          description: Account details retrieved successfully
          schema:
            $ref: "#/definitions/Account"
        "400":
          description: Invalid Account ID
        "404":
          description: Account not found
        "500":
          description: Internal Server Error

  /user/accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Account Transactions
      description: API for getting account transactions for current month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: Account ID
          type: string
          required: true
      responses:
        "200":
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Account ID
        "404":
          description: Account not found
        "500":
          description: Internal Server Error

  /user/accounts/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Transaction Details
      description: API for getting transaction details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: Account ID
          type: string
          required: true
        - in: path
          name: transactionId
          description: Transaction ID
          type: string
          required: true
      responses:
        "200":
          description: Transaction details retrieved successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid IDs
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

  /user/categories:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Available Categories
      description: Get list of available transaction categories used to populate the dropdown menu that appears when clicking the pencil icon next to the category field
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      responses:
        "200":
          description: Categories retrieved successfully for dropdown menu
          schema:
            type: array
            items:
              type: string
              enum: ["Food", "Shopping", "Bills", "Transport", "Entertainment"]
        "500":
          description: Internal Server Error

  /user/accounts/{accountId}/transactions/{transactionId}/category:
    patch:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Update Transaction Category
      description: API for updating transaction category. A pencil icon next to the category opens a dropdown menu containing predefined categories for selection
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: Account ID
          type: string
          required: true
        - in: path
          name: transactionId
          description: Transaction ID
          type: string
          required: true
        - in: body
          name: category
          description: New category selected from the dropdown menu
          required: true
          schema:
            $ref: "#/definitions/TransactionCategory"
      responses:
        "200":
          description: Category updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid request
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

  /user/accounts/{accountId}/transactions/{transactionId}/notes:
    patch:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Update Transaction Notes
      description: API for updating transaction notes. A pencil icon next to the note field opens a text input for editing
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: Account ID
          type: string
          required: true
        - in: path
          name: transactionId
          description: Transaction ID
          type: string
          required: true
        - in: body
          name: note
          description: New note entered in text input field
          required: true
          schema:
            $ref: "#/definitions/TransactionNote"
      responses:
        "200":
          description: Note updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid request
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Delete Transaction Notes
      description: API for deleting transaction notes
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: Account ID
          type: string
          required: true
        - in: path
          name: transactionId
          description: Transaction ID
          type: string
          required: true
      responses:
        "200":
          description: Note deleted successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid request
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    type: object
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user name

  Login:
    type: object
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  UserProfile:
    type: object
    properties:
      userName:
        type: string
      firstName:
        type: string
      lastName:
        type: string

  Account:
    type: object
    properties:
      accountId:
        type: string
        example: "x3448"
      accountType:
        type: string
        example: "Checking"
      balance:
        type: number
        format: double
        example: 48098.43
      description:
        type: string
        example: "Argent Bank Checking (x3448)"

  Transaction:
    type: object
    properties:
      transactionId:
        type: string
      date:
        type: string
        format: date
        example: "27/02/20"
      description:
        type: string
        example: "Golden Sun Bakery"
      amount:
        type: number
        format: double
        example: 8.00
      balance:
        type: number
        format: double
        example: 298.00
      type:
        type: string
        example: "Electronic"
      category:
        type: string
        example: "Food"
        description: "Category that can be modified by clicking the pencil icon which opens a dropdown menu with predefined options"
      note:
        type: string
        example: "lorem ipsum"
        description: "Note that can be edited by clicking the pencil icon which opens a text input field"

  TransactionCategory:
    type: object
    properties:
      category:
        type: string
        description: "Category to be selected from the predefined options in the dropdown menu"
        enum: ["Food", "Shopping", "Bills", "Transport", "Entertainment"]

  TransactionNote:
    type: object
    properties:
      note:
        type: string
        description: "Note that can be edited via text input after clicking the pencil icon"
